### PR TITLE
fixed image height in edge cases

### PR DESCRIPTION
**Pull request by nicokaiser**
The `justified-layout` library has an internal `edgeCaseTargetRowHeight` value, which is set to [`2 * layoutConfig.targetRowHeight`](https://github.com/flickr/justified-layout/blob/9d4db49cdbf45604c63a8b25293650af4fe952ab/lib/index.js#L39).

This means, that in some edge cases, when a very tall image needs to be put in its own row (e.g. in a narrow layout), the aspect ratio of the calculated box is different from the one of the image.

Bildschirmfoto 2024-02-02 um 11 31 50

In this example, the waterfall image needed to be displayed in its own row, but the height is larger than `2 * layoutConfig.targetRowHeight` (note the missing padding below the image). This is considered in the library's `height` attribute, **so by adding `height` and `overflow` attributes to the containers we clip images in these edge cases just a little bit**.

This could also be solved by setting `calculateItemsHeight`, but in some cases it might be preferred to avoid rows that are too tall.

### CODE REVIEW

**Comment by nk-o** [comment]
Interesting... But I don't like the `overflow` solution because it may break existing galleries, which already work without `overflow`.

Maybe it is better to add `height` using JS and also extend the CSS file to something like this?

```
.fj-gallery .fj-gallery-item > img {
  ...
  height: 100%;
  object-fit: cover;
}
```

And if your gallery requires `overflow`, you can add it using custom CSS on your own project. Everyone will be happy :)

**Comment by nk-o** [comment]
What about option named `calculateItemsHeight` - we created it mostly for galleries with captions. For example, this gallery is working because we recalculate rows - https://visualportfolio.co/justified-captions/

**Comment by nicokaiser** [comment]
The `object-fit` solution does not work, since the the height of the container (not the image) is set. 

Adding the `height` using JS would work for me (since I can add `overflow` via css), but it does not feel right to me, since – by the output of the library – the height actually _should_ be changed (i.e. the image is supposed to be cropped) in this (although rare) edge case.

Here is an example:

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>fjGallery | Flickr's Justified Gallery</title>
    <meta name="description" content="Flickr's justified images gallery layout" />
    <link href="css/demo.css" rel="stylesheet" />

    <!-- fjGallery -->
    <script src="../dist/fjGallery.js"></script>
    <link href="../dist/fjGallery.css" rel="stylesheet" />
  </head>
  <body>
    <div class="fj-gallery" style="width: 410px">
      <div class="fj-gallery-item">
        <img src="https://placehold.co/600x400" alt="" width="600" height="400" />
      </div>
      <div class="fj-gallery-item">
        <img src="https://placehold.co/400x600/F00/FFF" alt="" width="400" height="600" />
      </div>
      <div class="fj-gallery-item">
        <img src="https://placehold.co/600x428/0F0/000" alt="" width="600" height="428" />
      </div>
      <div class="fj-gallery-item">
        <img src="https://placehold.co/600x400" alt="" width="600" height="400" />
      </div>
    </div>

    <script>
      fjGallery(document.querySelectorAll(".fj-gallery"), {
        itemSelector: ".fj-gallery-item",
        transitionDuration: false,
        calculateItemsHeight: false,
        gutter: 10,
        rowHeight: 288,
        rowHeightTolerance: 0.25,
      });
    </script>
  </body>
</html>

```

**Comment by nicokaiser** [comment]
> What about option named `calculateItemsHeight`

I actually used this option before. It kind of solved this problem by basically overriding the library's `edgeCaseTargetRowHeight` behaviour (which might or might not be intended in this case). However it feels like unnecessary work in this case. And furthermore, it introduced a different bug, see #25.

**Comment by nicokaiser** [comment]
I just removed the `overflow` property, because it can be added via CSS. Regardless if it maybe should be added, this PR will less likely break compatibility with existing galleries now.

**Comment by nk-o** [comment]
I have checked it, and the height setting will break existing galleries, too. Mostly galleries with captions and option `calculateItemsHeight`.

**Comment by nicokaiser** [comment]
I see. So a possible workaround to solve the bug mentioned in https://github.com/nk-o/flickr-justified-gallery/pull/24#issuecomment-1923836341 could be setting `edgeCaseMaxRowHeight` to let's say `3 * self.options.rowHeight` in [`justifiedOptions`](https://github.com/nk-o/flickr-justified-gallery/blob/3e960cc2363f7562c3d84cc60a46556c3986a7fb/src/fjGallery.js#L231)?

This should at least help to avoid broken layouts with common aspect ratios (3:2 and 2:3 is quite a common one), right?

**Comment by nk-o** [comment]
Yes, the x3 multiplier will definitely resolve your issue, but this value is hardcoded in `justified-layout` lib. They haven't updated it for 4 years already, so I can fork it and use the forked version in our library.

**Pull request closed without merging**
